FROM openjdk:11.0.8-jdk-slim

COPY ./jicofo /home/jicofo
COPY ./jacocoagent.jar /home/jicofo/jacocoagent.jar

COPY ./jicofo-for-coverage.sh /home/jicofo/jicofo.sh
ENTRYPOINT ["/home/jicofo/jicofo.sh"]